[dev]
  port = 4000
  targetPort = 8080
  publish = "/apps/_site"
  command = "script/server"
  framework = "#custom"
[build]
  functions = "netlify/functions"
  command = "script/install && script/build && rm -rf apps/node_modules/hamljs/test/"
