#!/bin/bash
set -e -u
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

bundle install

# docker builder places this file so stop npm install from re-running
# all the time.
if [ ! -f "$DIR/../node_modules/.no-refresh" ] ; then
   npm install
fi
